apiVersion: v1
kind: Service
metadata:
  name: udagram-feed
  labels:
    app: udagram-feed
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: udagram-feed
---
apiVersion: v1
kind: Service
metadata:
  name: udagram-users
  labels:
    app: udagram-users
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: udagram-users
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-proxy
  name: udagram-proxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: udagram-proxy
  type: LoadBalancer
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-frontend
  name: udagram-frontend
  namespace: default
  selfLink: /api/v1/namespaces/default/services/udagram-frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: udagram-frontend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}