language: node_js
node_js:
  - 12

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-feed .
  - docker tag udagram-feed baninho/udagram-feed

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push baninho/udagram-feed
